### ISSUE TITLE
In update_quiz, the code @questionnaire.update_attributes(questionnaire_params) is unprotected mass assignment; fix it to whitelist the allowed parameters.  Ditto for

### ISSUE THREAD

**Issue by shalinshal** [shalinshal/expertiza#12]
Rails.logger.info(question.errors.messages.inspect) unless question.update_attributes(params[:question][question_key])

**Comment by danmenloz** [comment]
Apparently, this requirement has been already implemented. We need to wait for more information regarding this issue.
